# This is a basic workflow to help you get started with Actions

name: DIR

# Controls when the workflow will run
on:
  # Triggers the workflow on push Dev-Har
  push:
    branches: [ Dev-Dir ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install cowsay wget figlet git -y

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            figlet HelloWorld
            cowsay HelloHack
        shell: bash
        
      # Check My IP
      - name: Check My Ip
        run: curl ip.sb | cowsay -f dragon-and-cow
        shell: bash
        
      # Check Python Env
      - name: Check Python Env
        run: python --version | cowsay -f ghostbusters
        shell: bash
      # Check pip Env
      - name: Check pip env
        run: pip3 --version | cowsay
        shell: bash
        
